// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GFrame {
    
    /// <summary>
    /// UI框架相关的路径
    /// </summary>
    public class UIEditorPathConfig {
        /// <summary>
        /// 生成UI脚本的路径
        /// </summary>
        public static string ScriptGeneratorPath {
            get {
                return IOUtil.CreateDirIfNotExists(UnityEngine.Application.dataPath + "/" + ConfigUtil.LoadConfig<Setting>().UIScriptGeneratePath);
            }
        }
    }
}
